### ISSUE TITLE
Zoooom

### ISSUE THREAD

**Issue by Mister-Muffin** [Mr-Pine/XKCDFeed#1]
- [x] Bild anklicken dann groß und lesbar danke

**Comment by Mr-Pine** [comment]
- [ ] New View to view single comics
- [ ] Swipeable to see next/previous comic
- [ ] PopUp to go to a specific number (with Buttons for prev., next, first and latest)
- [ ] Zoomable / reset with double click
- [ ] Oh no pls help me

_Maybe implement separate ViewModel_
